### PR TITLE
Boilerplate Spec for master Branch

### PR DESCRIPTION
**Pull request by dblevins**
Generated boilerplate spec.  Feel free to merge, then refine.

 See https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release

### CODE REVIEW

**Comment by dblevins** [comment]
I think this PR is flawed.  Feel free to reject or see its a head start and merge/fix.

**Comment by pzygielo** [comment]
Shall this be included as module in top `pom.xml`?

**Comment by bshannon** [comment]
No.  It has a different version and a different lifecycle.

**Comment by pzygielo** [comment]
> No. It has a different version and a different lifecycle.

Will separate CI job be created then?

**Comment by bshannon** [comment]
To do what?

I'm not worried about "breaking the build" for the spec, and there's no testing for the spec.

**Pull request merged**
